name: "Vercel Setup"
description: "Install Vercel CLI and configure project settings"

inputs:
  vercel-token:
    description: "Vercel authentication token"
    required: true
  vercel-org-id:
    description: "Vercel organization ID"
    required: true
  vercel-project-id:
    description: "Vercel project ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify Vercel CLI
      shell: bash
      run: |
        # Output Vercel version (already installed in toolchain)
        echo "Vercel CLI version:"
        vercel --version

    - name: Prepare Vercel configuration
      shell: bash
      run: |
        # Initialize Vercel project configuration
        mkdir -p .vercel
        echo '{"orgId":"${{ inputs.vercel-org-id }}","projectId":"${{ inputs.vercel-project-id }}"}' > .vercel/project.json
        vercel pull --token=${{ inputs.vercel-token }}