version: "3.8"

services:
  app:
    # To pin to specific digest hash instead of tag, run:
    # docker pull mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    # docker inspect mcr.microsoft.com/devcontainers/base:ubuntu-22.04 --format='{{index .RepoDigests 0}}'
    # Then replace the image line below with: mcr.microsoft.com/devcontainers/base@sha256:<hash>
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    volumes:
      - config:/home/vscode/.config
      - cache:/home/vscode/.cache
      - vercel:/home/vscode/.local/share/com.vercel.cli
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    command: sleep infinity
    networks:
      - uspark-network

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - uspark-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  config:
  cache:
  vercel:
  postgres-data:

networks:
  uspark-network:
    driver: bridge
