name: "Vercel Build"
description: "Build application using Vercel and upload artifacts"

inputs:
  vercel-token:
    description: "Vercel authentication token"
    required: true
  vercel-org-id:
    description: "Vercel organization ID"
    required: true
  vercel-project-id:
    description: "Vercel project ID"
    required: true
  artifact-name:
    description: "Name for the build artifact"
    required: true

outputs:
  artifact-name:
    description: "Name of the uploaded artifact"
    value: ${{ inputs.artifact-name }}

runs:
  using: "composite"
  steps:
    - name: Setup Vercel
      uses: ./.github/actions/vercel-setup
      with:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-org-id: ${{ inputs.vercel-org-id }}
        vercel-project-id: ${{ inputs.vercel-project-id }}

    - name: Build application
      shell: bash
      run: vercel build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        include-hidden-files: true
        path: |
          .vercel/output
          turbo/apps/*/.next
        retention-days: 7
        overwrite: true
