name: "Vercel Build"
description: "Build application using Vercel and upload artifacts"

inputs:
  vercel-token:
    description: "Vercel authentication token"
    required: true
  vercel-org-id:
    description: "Vercel organization ID"
    required: true
  vercel-project-id:
    description: "Vercel project ID"
    required: true
  artifact-name:
    description: "Name for the build artifact"
    required: true
  build-env:
    description: "Build-time environment variables (key=value pairs, one per line)"
    required: false
    default: ""

outputs:
  artifact-name:
    description: "Name of the uploaded artifact"
    value: ${{ inputs.artifact-name }}

runs:
  using: "composite"
  steps:
    - name: Setup Vercel
      uses: ./.github/actions/vercel-setup
      with:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-org-id: ${{ inputs.vercel-org-id }}
        vercel-project-id: ${{ inputs.vercel-project-id }}

    - name: Build application
      shell: bash
      run: |
        # Build command with environment variables
        BUILD_CMD="vercel build"
        
        # Add build environment variables if provided
        if [ -n "${{ inputs.build-env }}" ]; then
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              # Parse key=value format and export for build
              KEY=$(echo "$line" | cut -d'=' -f1)
              VALUE=$(echo "$line" | cut -d'=' -f2-)
              export "$KEY=$VALUE"
              echo "Set build env: $KEY"
            fi
          done <<< "${{ inputs.build-env }}"
        fi
        
        # Execute build
        $BUILD_CMD

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        include-hidden-files: true
        path: |
          .vercel/output
          turbo/apps/*/.next
        retention-days: 7
        overwrite: true