# Claude Code Settings with Pre-commit Hooks

# Automatically run pre-commit checks before accepting edits
[[hooks]]
name = "pre-commit-quality-check"
type = "PostToolUse"
tools = ["Edit", "MultiEdit", "Write"]
script = """
# Run pre-commit checks on changed files
cd turbo && pnpm format
cd turbo && pnpm turbo run lint
cd turbo && pnpm check-types
"""

# Format TypeScript/JavaScript files after editing
[[hooks]]
name = "auto-format-ts"
type = "PostToolUse"
tools = ["Edit", "MultiEdit"]
matcher = "**/*.{ts,tsx,js,jsx}"
script = "cd turbo && pnpm format"

# Validate commit messages
[[hooks]]
name = "commit-message-check"
type = "PreToolUse"
tools = ["Bash"]
matcher = "**/git commit*"
script = """
echo "Checking commit message format..."
# This hook can trigger the commit-validator agent
"""

# Block commits if tests fail
[[hooks]]
name = "test-before-commit"
type = "PreToolUse"
tools = ["Bash"]
matcher = "**/git commit*"
script = """
cd turbo && pnpm vitest --run || (echo "Tests failed! Fix tests before committing." && exit 1)
"""