name: "Init PNPM"
description: "Initialize pnpm in turbo directory"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "22"
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: |
          - cwd: turbo
            args: [--frozen-lockfile, --strict-peer-dependencies]
