name: Docker Build

on:
  pull_request:
    paths:
      - 'toolchain/**'
      - '.devcontainer/**'
      - '.github/workflows/docker-*.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build toolchain image
        uses: docker/build-push-action@v5
        with:
          context: ./toolchain
          file: ./toolchain/Dockerfile
          target: toolchain
          push: false
          tags: uspark-toolchain:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build development image
        uses: docker/build-push-action@v5
        with:
          context: ./toolchain
          file: ./toolchain/Dockerfile
          target: development
          push: false
          tags: uspark-dev:test
          cache-from: type=gha
          cache-to: type=gha,mode=max