name: Turbo

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Lint
        run: npx -y @evilmartians/lefthook run pre-commit --all-files

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Test
        run: cd turbo && pnpm test

  build-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Build Cli
        run: cd turbo && pnpm -F makita-cli build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: turbo-build-${{ github.sha }}-cli
          path: turbo/apps/cli/dist
          retention-days: 7
          overwrite: true

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Build Web Application
        uses: ./.github/actions/vercel-build
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ vars.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ vars.VERCEL_PROJECT_ID_WEB }}
          artifact-name: turbo-build-${{ github.sha }}-web

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Build Web Application
        uses: ./.github/actions/vercel-build
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ vars.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ vars.VERCEL_PROJECT_ID_DOCS }}
          artifact-name: turbo-build-${{ github.sha }}-docs

  e2e:
    runs-on: ${{ matrix.os }}
    needs: build-cli
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: turbo-build-${{ github.sha }}-cli
          path: turbo/apps/cli/dist

      - name: Install CLI globally
        run: cd turbo/apps/cli/dist && npm install && npm link

      - name: Run E2E Tests
        run: cd e2e && make test

  # Database for preview environment
  database:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    permissions:
      deployments: write
    outputs:
      database-url: ${{ steps.branch.outputs.database-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Create Neon Branch and Run Migrations
        id: branch
        uses: ./.github/actions/neon-branch
        with:
          neon-api-key: ${{ secrets.NEON_API_KEY }}
          neon-project-id: ${{ vars.NEON_PROJECT_ID }}
          branch-name: "${{ github.head_ref }}"
          action: "create"

  # Deploy web application
  deploy-web:
    runs-on: ubuntu-latest
    needs: [build-web, database]
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: turbo-build-${{ github.sha }}-web

      - name: Deploy Web to Vercel
        id: deploy
        uses: ./.github/actions/vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ vars.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ vars.VERCEL_PROJECT_ID_WEB }}
          environment: preview
          deployment-env: web
          environment-variables: |
            DATABASE_URL=${{ needs.database.outputs.database-url }}
          meta-branch: ${{ github.head_ref }}
          meta-pr: ${{ github.event.pull_request.number }}

  # Deploy docs application
  deploy-docs:
    runs-on: ubuntu-latest
    needs: [build-docs]
    if: github.event_name == 'pull_request' && vars.VERCEL_PROJECT_ID_DOCS != ''
    permissions:
      pull-requests: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: turbo-build-${{ github.sha }}-docs

      - name: Deploy Docs to Vercel
        id: deploy
        uses: ./.github/actions/vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ vars.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ vars.VERCEL_PROJECT_ID_DOCS }}
          environment: preview
          deployment-env: docs
          meta-branch: ${{ github.head_ref }}
          meta-pr: ${{ github.event.pull_request.number }}
