# This is a config for E2B sandbox template.
# You can use template ID (w6qe4mwx23icyuytq64y) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("w6qe4mwx23icyuytq64y") # Sync sandbox
# sandbox = await AsyncSandbox.create("w6qe4mwx23icyuytq64y") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('w6qe4mwx23icyuytq64y')

dockerfile = "e2b.Dockerfile"
template_id = "w6qe4mwx23icyuytq64y"

# Environment variables for container runtime
[env]
# uSpark authentication token (required for file sync)
USPARK_TOKEN = "${USPARK_TOKEN}"

# Project ID to pull files from (set dynamically when creating sandbox)
PROJECT_ID = "${PROJECT_ID}"

# Claude API key for Claude Code CLI execution
CLAUDE_API_KEY = "${CLAUDE_API_KEY}"
